### ISSUE TITLE
Uncaught Error: Field must be inside a component decorated with reduxForm()

### ISSUE THREAD

**Issue by nicolazilio** [TeselaGen/openVectorEditor#891]
@tnrich

Hi there,

I've just upgraded to OVE v18.2.32 and bio-parsers v9.3.2 and I am experiencing a problem when double-clicking on a feature. This action should, and previously did, open the "Edit feature" window. Now, I get a blank page and the following error in the console

```
createField.js:42  Uncaught Error: Field must be inside a component decorated with reduxForm()
    at new r (createField.js:42:15)
    at bi (react-dom.production.min.js:135:172)
    at qa (react-dom.production.min.js:181:146)
    at Ws (react-dom.production.min.js:269:427)
    at Tc (react-dom.production.min.js:250:347)
    at Bc (react-dom.production.min.js:250:278)
    at Ic (react-dom.production.min.js:250:138)
    at yc (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ko (react-dom.production.min.js:122:325)
    at Xo (react-dom.production.min.js:123:61)
    at Yo (react-dom.production.min.js:122:428)
    at Le (react-dom.production.min.js:292:101)
    at Xt (react-dom.production.min.js:73:352)
```

If I check your demo at <https://teselagen.github.io/openVectorEditor/#/Editor>, I can open the "Edit feature" window no problem. Provided that my project is a lightly edited version of <https://github.com/tnrich/ove-react-demo-repo>, I'm not sure whether the problem lies at my end or with OVE.

**Comment by tnrich** [comment]
@nicolazilio hmm ya maybe try updating the ove-react-demo-repo to the latest version of ove + related deps and see if everything works there?

**Comment by nicolazilio** [comment]
Thanks, I will investigate further!

**Comment by nicolazilio** [comment]
A quick update on this topic. I upgraded to open-vector-editor ^18.3, and now the problem is gone. I love when that happens :).
